### ISSUE TITLE
Catch errors and notify user

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-ui#102]
Whenever an error happen in the UI, there is only the error message on the console from dev tools. We should provide some means to catch those errors and notify the user so he can take some action (like pressing again transfer buttom)

## Implementation details

- Create component that will render the catched errors and notify the user
- Create some sort of dictionary of possible errors and corresponding messages
- Test implementation to be sure catching errors is working properly

**Comment by itsbobbyzzz168** [comment]
Sygma UI will be replaced with Sygma widget. Closing.
