### ISSUE TITLE
Unable to remind user to change network automatically

### ISSUE THREAD

**Issue by fox-222** [sygmaprotocol/sygma-ui#105]
Click "Connect Wallet" on the page https://transfer-ui.test.buildwithsygma.com/transfer.

If the wallet connected is not on Georli network, the following error will appear, and the user should be prompted to switch networks:

```
TypeError: Cannot read properties of undefined (reading 'confirmations')
    at e.value (Sygma.ts:147:33)
    at Bridge.tsx:38:21
    at us (react-dom.production.min.js:211:320)

```

**Comment by itsbobbyzzz168** [comment]
Sygma UI will be replaced with Sygma widget. Closing.
