### ISSUE TITLE
Consider upgrading sygma-sdk-core to version 2.1.0?

### ISSUE THREAD

**Issue by cppfuns** [sygmaprotocol/sygma-ui#149]
"@buildwithsygma/sygma-sdk-core": "1.3.0",

**Comment by alexmmueller** [comment]
Thank you @cppfuns! SDK dependency update is already in the works and will be released shortly.

**Comment by itsbobbyzzz168** [comment]
Sygma UI will be replaced with Sygma widget. Closing.
