### ISSUE TITLE
Add support for shared configuration [UI]

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-ui#58]
Sygma UI needs to be refactored so its supports the new shared configuration.

## Implementation details

- Add support for loading shared configuration from IPNS URL
- Reduce old configuration to properties that are not migrated to shared configuration
- Add logic for merging two configurations

## Testing details

- Write unit tests for merging configurations

## Acceptance Criteria

[ ] Successful devnet shared configuration loading
[ ] Delivered to the TestNet

**Comment by P1sar** [comment]
There is one task now where Anton can start getting him self familiar with, and we will try to help him as we can, unfortunately now everyone is very busy, moreover Nicolas has a vacation.
Please make your self familiar with next Proposal that we are now implementinghttps://www.notion.so/chainsafe/Shared-configuration-95a62a2ed8ac43e7855f11b0a49452ee. Generally sygma-ui is the only place left where this should be implemented.
Here is the repo that contains shared configuration and pipelines to update it https://github.com/sygmaprotocol/sygma-shared-configuration
Sygma-ui now using config-server as backend for most of the param it shuld start using shared config.
The isssue is here https://github.com/sygmaprotocol/sygma-ui/issues/58
IPNS config example to test with is here https://cloudflare-ipfs.com/ipns/k51qzi5uqu5dhl2gkm5u2pgqjey03ggmwc23i58tgqc6aespewctzcgqbu1nph
It might have some problems fetching data from IPNS, so what I believe, you should do first (to make development easier) is to implement mocking interface for fetching that fetch params from local file when you ran it in debug mode.
