### ISSUE TITLE
Delayed prompts from MetaMask + not sure if UI is still running (ERC-20 test transfers)

### ISSUE THREAD

**Issue by haochizzle** [sygmaprotocol/sygma-ui#76]
Tested this with Mumbai -> Moombase and vice versa with ERC-20 transfers using the [transfer UI](https://transfer-ui.test.buildwithsygma.com/transfer). Both were completed eventually after multiple tries. 

## Current Behavior
* MetaMask prompts are extremely delayed, if at all, for both `approve` and `deposit` txs 
* Not sure if the dapp was still running/processing in the BG due to static UI page

## Expected Behavior
* Ideally, MetaMask prompts are... prompt
  * Multiple times, I navigated away from the page altogether only to be prompted out of nowhere to complete either the approval or deposit transactions 
  * Txs would abort in the UI after a delayed amount of time

## Possible Solution
* A spinning circle or animation letting me know if UI / dapp is still working as expected or if it has aborted, would be great

**Comment by P1sar** [comment]
Thanks for reporting. We already working on this problem in this issue [here](https://github.com/sygmaprotocol/sygma-ui/issues/77)

**Comment by P1sar** [comment]
Thanks for reporting. We already working on this problem in this issue https://github.com/sygmaprotocol/sygma-ui/issues/77
