### ISSUE TITLE
NFT UI not working properly

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-ui#80]
## Expected Behavior
UI displays erc721 tokens that are available for bridging.

## Current Behavior
UI is stuck in loading animation because of the error shown in the screenshot below:
#### Mumbai
![image.png](https://images.zenhubusercontent.com/5d89fef759191331a1878a20/1e7ea60a-01c3-4868-b01a-733f650d1c04)

#### Moonbase
![image.png](https://images.zenhubusercontent.com/5d89fef759191331a1878a20/1cffab82-ac18-4fdf-9560-e5df70e7f911)

## Steps to Reproduce (for bugs)

1. Mint erc721 from faucet 
2. Open [NFT Bridge UI on testnet](https://transfer-ui.test.buildwithsygma.com/nft_transfer)

**Comment by itsbobbyzzz168** [comment]
No longer applicable.
