### ISSUE TITLE
Enable and update modal in case of unsupported network

### ISSUE THREAD

**Issue by enemycnt** [sygmaprotocol/sygma-ui#95]
## Implementation Details
- If the user's device is not connected to a supported network, display a modal with a message informing the user that network is not supported.
- The modal should have a button that allows the user to dismiss it and return to the previous screen.

## Testing Details

- Test the modal when the user's device is connected to a network that is not supported.
- Test the modal when the user's device is connected to a supported network.

## Acceptance Criteria
- The modal should have a button that allows the user to dismiss it and return to the previous screen.
- The modal should not be displayed when the user's device is connected to a supported network.

**Comment by haochizzle** [comment]
Error has been reported by multiple users on Discord, including the [most recent example](https://discord.com/channels/999966147644493824/999966148714053664/1122513096053882962). @alexmmueller @MakMuftic

**Comment by haochizzle** [comment]
@MakMuftic maybe as a holdover, can we add a disclaimer at the top of the testnet/devnet transfer UI saying something like:

:::info
Please be aware that MetaMask must already be switched to a supported network (Goerli, Sepolia, etc.) before clicking on the "Connect Wallet" button.
:::

**Comment by alexmmueller** [comment]
@P1sar & @MakMuftic Can we please increase priority of the bug and fix it quickly?

**Comment by itsbobbyzzz168** [comment]
I've increased priority and will drop in the dev chanel

**Comment by wainola** [comment]
Update: I will create an error message as a modal, showing a list of the current suported networks, hence users will know which are the networks you can connect with the transfer UI
